import { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from 'expo-camera';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParamList, 'ScanProvision'>;

interface ProvisioningPayload {
  v: number;
  mqttHost: string;
  mqttPort: number;
  orgId: string;
  deviceKey: string;
  apiKey: string;
}

// Scanning this QR code (generated by the web dashboard's provisioning flow,
// see backend/src/services/qrCode.service.js) is how a field technician gets
// a device's broker address + one-time credentials without typing anything
// by hand - the whole point of the "standardized provisioning" flow.
export function ScanProvisionScreen({ navigation }: Props) {
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState<ProvisioningPayload | null>(null);
  const [error, setError] = useState<string | null>(null);

  function handleScan({ data }: BarcodeScanningResult) {
    if (scanned) return;
    try {
      const payload = JSON.parse(data) as ProvisioningPayload;
      if (!payload.deviceKey || !payload.apiKey) throw new Error('missing fields');
      setScanned(payload);
      setError(null);
    } catch {
      setError('That QR code is not a valid Bem Control device provisioning code.');
    }
  }

  if (!permission) return null;

  if (!permission.granted) {
    return (
      <View style={styles.center}>
        <Text style={styles.message}>Camera access is needed to scan a device's QR code.</Text>
        <TouchableOpacity style={styles.button} onPress={requestPermission}>
          <Text style={styles.buttonText}>Grant camera access</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (scanned) {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Device credentials</Text>
        <View style={styles.card}>
          <Row label="Device key" value={scanned.deviceKey} />
          <Row label="MQTT broker" value={`${scanned.mqttHost}:${scanned.mqttPort}`} />
          <Row label="API key" value={scanned.apiKey} mono />
        </View>
        <Text style={styles.hint}>
          Confirm the physical device has these credentials configured (via its captive-portal
          setup page or serial console), then mark it installed.
        </Text>
        <TouchableOpacity style={styles.button} onPress={() => navigation.goBack()}>
          <Text style={styles.buttonText}>Done</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.linkButton} onPress={() => setScanned(null)}>
          <Text style={styles.linkText}>Scan another</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <CameraView
        style={styles.camera}
        barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
        onBarcodeScanned={handleScan}
      />
      {error && <Text style={styles.error}>{error}</Text>}
    </View>
  );
}

function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={[styles.rowValue, mono && styles.mono]} numberOfLines={1}>
        {value}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#111827', padding: 16, paddingTop: 56 },
  camera: { flex: 1, borderRadius: 12, overflow: 'hidden' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  message: { color: '#374151', textAlign: 'center', marginBottom: 16 },
  title: { color: '#fff', fontSize: 18, fontWeight: '700', marginBottom: 16 },
  card: { backgroundColor: '#1f2937', borderRadius: 10, padding: 14, marginBottom: 16 },
  row: { marginBottom: 10 },
  rowLabel: { color: '#9ca3af', fontSize: 11, marginBottom: 2 },
  rowValue: { color: '#fff', fontSize: 13 },
  mono: { fontFamily: 'Courier' },
  hint: { color: '#9ca3af', fontSize: 12, marginBottom: 20 },
  button: { backgroundColor: '#26654f', borderRadius: 8, paddingVertical: 12, alignItems: 'center' },
  buttonText: { color: '#fff', fontWeight: '600' },
  linkButton: { alignItems: 'center', marginTop: 14 },
  linkText: { color: '#a7f3d0', fontSize: 13 },
  error: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    color: '#fff',
    backgroundColor: '#991b1b',
    padding: 10,
    borderRadius: 8,
    textAlign: 'center',
  },
});
