#!/usr/bin/env bash
#
# Embeds mosquitto/certs/ca.crt (generated by generate-dev-certs.sh) into a
# C header the ESP32 firmware includes directly, so WiFiClientSecure can
# verify the broker's certificate chain during the TLS handshake. Every
# device in the fleet ships the same CA header - it only changes if the
# broker's CA is rotated, which is the "reusable firmware config" part of
# the standardized provisioning flow.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CA_CERT="$ROOT_DIR/mosquitto/certs/ca.crt"
OUT_HEADER="$ROOT_DIR/firmware/include/ca_cert.h"

if [[ ! -f "$CA_CERT" ]]; then
  echo "ERROR: $CA_CERT not found. Run 'npm run certs:generate' from the repo root first." >&2
  exit 1
fi

{
  echo "// Auto-generated by scripts/generate-firmware-ca-header.sh - do not edit by hand."
  echo "// Re-run that script after rotating mosquitto/certs/ca.crt."
  echo "#pragma once"
  echo
  echo "static const char BEM_CONTROL_CA_CERT[] PROGMEM = R\"EOF("
  cat "$CA_CERT"
  echo ")EOF\";"
} > "$OUT_HEADER"

echo "Wrote $OUT_HEADER"
